### ISSUE TITLE
Warning: Undefined property: Magepow\Sizechart\Model\Cron::$cacheTypeList

### ISSUE THREAD

**Issue by magiccart** [magepow/magento2-sizechart#6]
When it runs we get the error: "Warning: Undefined property: Magepow\Sizechart\Model\Cron::$cacheTypeList in vendor/magepow/sizechart/Model/Cron.php

**Comment by TuVanDev** [comment]
Hi @magiccart. I'm currently working on a site that used this module, and they are impressed with the features it offers. Therefore, I would like to contribute to resolving a few issues related to this issue.

The original code:
```
class Cron
{
    public function __construct(
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\App\Cache\TypeListInterface $cacheTypeList,
        \Magento\Framework\App\Cache\Frontend\Pool $cacheFrontendPool
    ) {
        $this->_cacheTypeList = $cacheTypeList;
        $this->_cacheFrontendPool = $cacheFrontendPool;
    }

    public function flushCache()
    {
        //...
        foreach ($types as $type) {
            $this->cacheTypeList->cleanType($type);
        }
        foreach ($this->cacheFrontendPool as $cacheFrontend) {
            $cacheFrontend->getBackend()->clean();
        }
    }
}
```
1. Since the `cacheTypeList` property wasn't declared, it caused the error. Additionally, the `cacheFrontendPool` property was also not declared. As a result, it is necessary to fix the `cacheFrontendPool` property as well.
2. The Magento framework adheres to the PSR2 Coding Standards for PHP, which [states](https://www.php-fig.org/psr/psr-2/#:~:text=4.2.-,Properties):
> 4.2. Properties
Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

Hence, to follow best practices, it is recommended that we should not declare properties with a single underscore prefix.
3. The `__construct()` method has an unused parameter named 'context', which should be removed since it serves no purpose.

To address these issues, the code should be refactored as follows:
```
class Cron
{
    private $cacheTypeList;

    private $cacheFrontendPool;

    public function __construct(
        \Magento\Framework\App\Cache\TypeListInterface $cacheTypeList,
        \Magento\Framework\App\Cache\Frontend\Pool $cacheFrontendPool
    ) {
        $this->cacheTypeList = $cacheTypeList;
        $this->cacheFrontendPool = $cacheFrontendPool;
    }

    public function flushCache()
    {
        //...
        foreach ($types as $type) {
            $this->cacheTypeList->cleanType($type);
        }

        foreach ($this->cacheFrontendPool as $cacheFrontend) {
            $cacheFrontend->getBackend()->clean();
        }
    }
}
```
 Cheers!

**Comment by magiccart** [comment]
@TuVanDev If possible please help me with the new pull I will merge it.
Thanks for contributed.
